# Generated by Django 4.2 on 2024-05-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maze',
            name='drawing',
            field=models.JSONField(),
        ),
    ]
